Fix facturae creation test, setting some values to default elements
pedrobaeza/l10n-spain pull request #8
Opened 2016-09-29 15:30 UTC by elacunza

This should make travis happy

2016-09-29 17:08 UTC, elacunza commented
Ok a ver qué tal ahora

2016-09-29 17:13 UTC, pedrobaeza requested changes
Una última cosa: junta todos los commits en uno para no ensuciar mucho el historial de commits y poniendo mensaje en inglés

2016-09-29 17:13 UTC, pedrobaeza commented on l10n_es_facturae/tests/test_l10n_es_facturae.py
> +        main_partner.country_id = self.ref('base.us'),
Por qué país Estados Unidos y no España?

2016-09-29 17:13 UTC, pedrobaeza commented on l10n_es_facturae/tests/test_l10n_es_facturae.py
> +        main_company = self.env['res.company'].search([['id', '=', self.ref('base.main_company')]])
Esto se hace así directamente:
```
main_company = self.env.ref('base.main_company')
```

2016-09-29 18:01 UTC, elacunza commented on l10n_es_facturae/tests/test_l10n_es_facturae.py
> +        main_company = self.env['res.company'].search([['id', '=', self.ref('base.main_company')]])
Ok, se nota que tengo que engrasar mi Odoo bastante todavía... :)

2016-09-29 18:04 UTC, elacunza commented on l10n_es_facturae/tests/test_l10n_es_facturae.py
> +        main_partner.country_id = self.ref('base.us'),
El motivo es que en el XML con el que se compara el resultado del test, está como Estados Unidos; he intentado hacer los cambios mínimos para que los tests funcionen. 

Podríamos cambiar el XML para que indique España y una provincia española, pero entiendo que es posible que una empresa estadounidense genere una facturae a una empresa española...

2016-09-29 18:05 UTC, elacunza commented
Ok mañana por la mañana miro para hacer los cambios, estoy ya fuera de la oficina.

2016-09-30 07:37 UTC, closed without merging

2016-09-30 07:40 UTC, pedrobaeza commented on l10n_es_facturae/tests/test_l10n_es_facturae.py
> +        main_partner.country_id = self.ref('base.us'),
Ya recuerdo... era por no tener que tener instalado el l10n_es_toponyms, ya que hace falta la provincia y las de EEUU vienen de base.

2016-09-30 07:49 UTC, elacunza commented
Parece que soy incapaz de hacer push del rebase con un único commit, lo siento :)